
    application:
        name: FOOD-CATALOG-SERVICE
    datasource:
        url: jdbc:mysql://localhost:3306/foodcatalogdb
        username: root
        password: 12345
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

server:
    port: 9092

