apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      - job_name: 'eureka-server'
        static_configs:
          - targets: ['eureka-service:8761']
        metrics_path: '/actuator/prometheus'
      
      - job_name: 'restaurant-service'
        static_configs:
          - targets: ['restaurant-service:9091']
        metrics_path: '/actuator/prometheus'
      
      - job_name: 'food-catalogue-service'
        static_configs:
          - targets: ['foodcatalogue-service:9092']
        metrics_path: '/actuator/prometheus'
      
      - job_name: 'user-service'
        static_configs:
          - targets: ['user-service:9093']
        metrics_path: '/actuator/prometheus'
      
      - job_name: 'order-service'
        static_configs:
          - targets: ['order-service:9094']
        metrics_path: '/actuator/prometheus'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
        - name: prometheus-storage
          mountPath: /prometheus
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      - name: prometheus-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
  type: NodePort