server:
  port: 9094

eureka:
  service-url:
    defaultZone: http://localhost:8761/eureka/

application:
  name: ORDER-SERVICE
  data:
    url: mongodb://localhost:27017/orderdb
    host: localhost
    port: 27017
    database: orderdb
    repositories:
      enabled: true
